# This is a basic workflow to help you get started with Actions

name: ch generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/1 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "suning520999@gmail.com"
          git config --global user.name "sun520999"
      

      - name: Main
        run: |
          pwd
          chmod +x sh/ch1.sh
          ./sh/ch1.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch2.sh
          ./sh/ch2.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch3.sh
          ./sh/ch3.sh
     
      - name: Main
        run: |
          pwd
          chmod +x sh/ch4.sh
          ./sh/ch4.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch5.sh
          ./sh/ch5.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch6.sh
          ./sh/ch6.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch7.sh
          ./sh/ch7.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch8.sh
          ./sh/ch8.sh

      - name: Main
        run: |
          pwd
          chmod +x sh/ch9.sh
          ./sh/ch9.sh
                
      - name: Main
        run: |
          pwd
          chmod +x sh/ch10.sh
          ./sh/ch10.sh
          
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "link is updated"
          git push
