name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Get aljazeera.m3u8
      run: |
        touch ./aljazeera.m3u8
        sudo cat >./aljazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=-upyPouRrB8)
        EOL
    - name: Get abcau.m3u8
      run: |
        touch ./abcau.m3u8
        sudo cat >./abcau.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=W1ilCy6XrmI)
        EOL
    - name: Get abcus.m3u8
      run: |
        touch ./abcus.m3u8
        sudo cat >./abcus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=w_Ma8oQLmSM)
        EOL
    - name: Get africanews.m3u8
      run: |
        touch ./africanews.m3u8
        sudo cat >./africanews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=NQjabLGdP5g)
        EOL
    - name: Get Arirang.m3u8
      run: |
        touch ./Arirang.m3u8
        sudo cat >./Arirang.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=52unCHc6AV4)
        EOL
    - name: Get DW.m3u8
      run: |
        touch ./DW.m3u8
        sudo cat >./DW.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=4tbh25K-vO8)
        EOL
    - name: Get ebcyoyo.m3u8
      run: |
        touch ./ebcyoyo.m3u8
        sudo cat >./ebcyoyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/c/yoyotvebc/live)
        EOL
    - name: Get euronews.m3u8
      run: |
        touch ./euronews.m3u8
        sudo cat >./euronews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g --proxy socks4://114.34.115.110:5678/ https://www.youtube.com/watch?v=sPgqEHsONK8)
        EOL
    - name: Get france24.m3u8
      run: |
        touch ./france24.m3u8
        sudo cat >./france24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=aHh8rA0hks8)
        EOL
    - name: Get hyxw.m3u8
      run: |
        touch ./hyxw.m3u8
        sudo cat >./hyxw.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/channel/UCp2f7tGJGN6R9Muxipem8Nw/live)
        EOL
    - name: Get ipanda.m3u8
      run: |
        touch ./ipanda.m3u8
        sudo cat >./ipanda.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/iPandaChannel/live)
        EOL
    - name: Get tvbsnews.m3u8
      run: |
        touch ./tvbsnews.m3u8
        sudo cat >./tvbsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=V0WxUakDV7M)
        EOL
    - name: Get PTS.m3u8
      run: |
        touch ./PTS.m3u8
        sudo cat >./PTS.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g --proxy socks4://210.61.216.66:33990/ https://www.youtube.com/watch?v=JAzRXylm3M0)
        EOL
    - name: Get parliamentarytv1.m3u8
      run: |
        touch ./parliamentarytv1.m3u8
        sudo cat >./parliamentarytv1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=PQLMD4iHhG8)
        EOL
    - name: Get parliamentarytv2.m3u8
      run: |
        touch ./parliamentarytv2.m3u8
        sudo cat >./parliamentarytv2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=T8dcZHk4xWs)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
